export const emojis = [
  { icon: '🧙‍♂️', name: '魔法使い', description: '詠唱する者、召喚者' },
  { icon: '🔥', name: '炎', description: '魔力の爆発、闇の力' },
  { icon: '🌑', name: '新月', description: '闇の象徴、隠された力' },
  { icon: '🩸', name: '血', description: '契約の儀式、禁忌' },
  { icon: '⚡', name: '稲妻', description: 'エネルギー暴走、衝撃' },
  { icon: '🕯️', name: 'ロウソク', description: '魔法陣に灯す儀式の火' },
  { icon: '🧿', name: '邪眼', description: '魔除け、呪い返し' },
  { icon: '🦴', name: '骨', description: '死と再生、暗黒の力' },
  { icon: '🕸️', name: 'クモの巣', description: '禁断の地、封印' },
  { icon: '🪄', name: '魔法の杖', description: '詠唱、魔力の媒介' },
  { icon: '🛡️', name: '盾', description: '結界、防御魔法' },
  { icon: '💀', name: 'ドクロ', description: '死神、終焉のシンボル' },
  { icon: '🌪️', name: '竜巻', description: 'カオスそのもの' },
  { icon: '🛐', name: '礼拝の場', description: '召喚陣、儀式の舞台' },
  { icon: '✝️', name: '十字架', description: '聖別、禁忌のシンボル、破壊と再生' },
  { icon: '🩻', name: '骨格レントゲン', description: 'スケルトン魔法・蘇生' },
  { icon: '🧛', name: '吸血鬼', description: '闇の眷属、呪われし者' },
  { icon: '🔮', name: '水晶玉', description: '未来視、異界との交信' },
  { icon: '🌌', name: '銀河', description: '宇宙魔法、無限の混沌' },
  { icon: '🖋️', name: '羽ペン', description: '禁断の契約書にサイン' },
  { icon: '🌓', name: '半月', description: '二重性、闇と光の狭間' },
  { icon: '✨', name: '煌めき', description: '魔力のきらめき、祝福' },
  { icon: '✍️', name: '誓約の印', description: '誓い、呪文刻印' },
  { icon: '🌀', name: '渦巻き', description: '精神崩壊、混沌の象徴' },
];
